"""Write evidence/SEPOLIA_RESULTS.md: deployed addresses, every lifecycle transaction with its hash and
gas, the live attacks, the always-on key holder and the issuer-threshold experiment, from reports/."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "reports"
ld = lambda n: json.loads((R / n).read_text()) if (R / n).exists() else None
ETHERSCAN = "https://sepolia.etherscan.io"

summ, txs, agent, thr = ld("sepolia-summary.json"), ld("sepolia.json"), ld("agent-heartbeats.json"), ld("threshold-live.json")
dep = summ["deployment"]
out = ["# Live run on Ethereum Sepolia", "",
       "Generated by `scripts/sepolia_report_md.py` from `reports/`. Raw logs: `evidence/logs/sepolia-*.log`;",
       "Foundry broadcasts: `broadcast/*/11155111/`.", "", "## Deployed contracts", "",
       "| Contract | Address |", "|---|---|"]
for k in ("factory", "vaultImplementation", "livenessRegistry", "livenessVerifier", "ageVerifier",
          "demoERC20", "demoERC721", "demoERC1155"):
    out.append(f"| {k} | [`{dep[k]}`]({ETHERSCAN}/address/{dep[k]}) |")
out += ["", f"Parameters: minPeriod {dep['minPeriod']} s, authWindow {dep['authWindow']} s, "
        f"aggregator min epoch {dep['aggMinEpoch']} s, lookback {dep['aggLookback']} epochs.", ""]
lc = summ["lifecycle"]
out += ["## Lifecycle", "", f"{lc['transactions']} transactions, {lc['reverted']} reverted, "
        f"{lc['totalGas']:,} gas in total; largest deviation from the Foundry benchmark where state matches: "
        f"{lc['maxDeviationPct']}%.", "", "| # | Function | Gas | Status | Transaction |", "|---|---|---|---|---|"]
for i, t in enumerate(txs, 1):
    out.append(f"| {i} | `{t['function']}` | {t['gasUsed']:,} | {t['status']} | [{t['hash'][:12]}…]({ETHERSCAN}/tx/{t['hash']}) |")
at = summ["attacks"]
out += ["", "## Attacks", "", f"Off-chain: {at['offchainEditsRejected']}/{at['offchainEditsTotal']} edits of the "
        "production credential failed at proof generation (`reports/attacks-offchain.json`).", "",
        f"On-chain (calls against the deployed contracts): {at['onchainRejected']} rejected, all with the expected "
        f"error: {at['onchainAllAsExpected']}.", "", "| Attack | Rejected with |", "|---|---|"]
out += [f"| {a['attack']} | `{a['rejectedWith']}` |" for a in at["onchain"]]
if agent:
    out += ["", "## Always-on key holder", "",
            f"The human proved life once at {agent['humanLastProofOfLife']}; the key then sent {len(agent['heartbeats'])} "
            f"heartbeats ({agent['gasPerHeartbeat']} gas each). The deadline froze {agent['deadlineFrozenAfterSec']} s after "
            f"the proof at tL + ΔL = {agent['theoreticalCapOnDeadline']}; {agent['heartbeatsAfterFreeze']} later heartbeats "
            f"did not move it. Status matches theory: {agent['statusMatchesTheory']}; deadline never above the cap: "
            f"{agent['deadlineNeverExceedsCap']}; final status: {agent['final']['status']}.", "",
            "| s after proof | status | deadline | gas | transaction |", "|---|---|---|---|---|"]
    for b in agent["heartbeats"]:
        h = b.get("hash", "")
        out.append(f"| {b['secondsAfterProof']} | {b['status']} | {b['deadline']} | {b.get('gasUsed', '')} | "
                   + (f"[{h[:12]}…]({ETHERSCAN}/tx/{h})" if h else "") + " |")
if thr:
    out += ["", "## Issuer threshold (2 of 3)", "",
            f"- One issuer alone via `proveLife`: {thr['aloneSingle']}.",
            f"- One issuer alone via `proveLifeMulti`: {thr['aloneMulti']}.",
            f"- Two issuers accepted {thr['multiAccepted']} times (A+B, then B+C with A unavailable), gas {thr['multiGas']}:"]
    out += [f"  [{h[:12]}…]({ETHERSCAN}/tx/{h})" for h in thr["multiTx"]]
    out += [f"- `setBindingThreshold` gas: {thr['setThresholdGas']}."]
(ROOT / "evidence" / "SEPOLIA_RESULTS.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print("wrote evidence/SEPOLIA_RESULTS.md")
